### See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md for comprehensive
### documentation of the options in this file

[buildPlans.iosevka-code]
family = "IosevkaCode"
spacing = "normal"
serifs = "slab"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-code.variants]
inherits = "ss17"

[buildPlans.iosevka-code.variants.design]
capital-a = "straight-top-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "short-serifed"
capital-j = "serifed-both-sides"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-t = "motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
g = "double-storey-open"
h = "straight-motion-serifed"
r = "serifed"
t = "standard"
asterisk = "turn-hex-mid"
question = "corner"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-code.variants.italic]
capital-a = "curly-top-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "straight-top-left-and-bottom-right-serifed"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "open-swash"
capital-r = "standing-open-motion-serifed"
capital-s = "serifless"
capital-t = "serifless"
capital-v = "curly-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "cursive"
a = "single-storey-tailed"
c = "serifless"
g = "double-storey-open"
h = "tailed-serifless"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
l = "serifed-diagonal-tailed"
n = "tailed-motion-serifed"
p = "eared-motion-serifed"
q = "straight-motion-serifed"
r = "top-serifed"
t = "diagonal-tailed-short-neck"
y = "cursive-motion-serifed"
one = "base-long-top-serif"
four = "open"
six = "open-contour"
seven = "bend-serifless-crossbar"
nine = "open-contour"
diacritic-dot = "round"
punctuation-dot = "round"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-code.ligations]
inherits = "dlig"

[buildPlans.iosevka-code.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-code.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-code.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-code.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-code.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-code.slopes.italic]
angle = 6.3
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-terminal]
family = "IosevkaTerminal"
spacing = "term"
serifs = "slab"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-terminal.variants]
inherits = "ss17"

[buildPlans.iosevka-terminal.variants.design]
capital-a = "straight-top-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "short-serifed"
capital-j = "serifed-both-sides"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-t = "motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
g = "double-storey-open"
h = "straight-motion-serifed"
r = "serifed"
t = "standard"
asterisk = "turn-hex-mid"
question = "corner"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-terminal.variants.italic]
capital-a = "curly-top-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "straight-top-left-and-bottom-right-serifed"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "open-swash"
capital-r = "standing-open-motion-serifed"
capital-s = "serifless"
capital-t = "serifless"
capital-v = "curly-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "cursive"
a = "single-storey-tailed"
c = "serifless"
g = "double-storey-open"
h = "tailed-serifless"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
l = "serifed-diagonal-tailed"
n = "tailed-motion-serifed"
p = "eared-motion-serifed"
q = "straight-motion-serifed"
r = "top-serifed"
t = "diagonal-tailed-short-neck"
y = "cursive-motion-serifed"
one = "base-long-top-serif"
four = "open"
six = "open-contour"
seven = "bend-serifless-crossbar"
nine = "open-contour"
diacritic-dot = "round"
punctuation-dot = "round"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-terminal.ligations]
inherits = "dlig"

[buildPlans.iosevka-terminal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-terminal.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-terminal.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-terminal.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-terminal.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-terminal.slopes.italic]
angle = 6.3
shape = "italic"
menu = "italic"
css = "italic"
