# Get app IDs with: swaymsg -t get_tree  (or run: swaymsg -t get_tree | grep app_id)
# assign [app_id="msedge-_ompifgpmddkgmclendfeacglnodjjndh-Profile_1"] workspace number 1
assign [title="Microsoft Teams"] workspace number 1
# assign [app_id="microsoft-edge"] workspace number 2
# assign [app_id="code"] workspace number 3
# assign [app_id="zed"] workspace number 3
# assign [app_id="org.wezfurlong.wezterm"] workspace number 4

# Force certain windows to float
for_window [window_role="pop-up"] floating enable
for_window [app_id="pavucontrol"] floating enable
for_window [title="Picture-in-Picture"] floating enable
